class FunctionNotFoundError(Exception):
	pass

class FunctionFailedError(Exception):
	pass
